service: prueba-abp3

package:
  exclude:
    - ./**
  include:
    - handlers/**

custom:
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  s3_bucket: image-store-rekog-abp
  dynamo_rekog: rekog-index
  dynamo_log: log-registry


provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  timeout: 30
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  role: arn:aws:iam::945154355127:role/lambda-admin


functions:
  picture-indexation:
    runtime: python2.7
    handler: handlers/picture-indexation.lambda_handler
    events:
      - s3: ${self:custom.s3_bucket}

  rekognition-ABP:
    handler: handlers/rekognition-ABP.handle
    events:
      - http:
            path: /rekog
            method: post
            cors: true
 
  upload_new_user-ABP:
    handler: handlers/new_user.handle
    events:
      - http:
            path: /picture
            method: post
            cors: true

resources:
  Resources:
    RekogIndexation:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: RekognitionId
            AttributeType: S
        KeySchema:
          - AttributeName: RekognitionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.dynamo_rekog}

    LogRegist:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: logId
            AttributeType: S
        KeySchema:
          - AttributeName: logId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.dynamo_log}
